from pydantic import BaseModel
from typing import Optional

class PromptsMeta(BaseModel):
    blueprint_version: int
    last_updated_by: str
    last_updated_at: str

class CharacterSheetEntry(BaseModel):
    """Character reference sheet. Generated via Flux Klein 9B pure T2I (no refs).
    Prompt is a natural-language paragraph covering all reference-sheet views.
    """
    prompt_type: str = "flux_klein_t2i"
    prompt: Optional[str] = None
    output_path: Optional[str] = None
    status: str = "pending"
    generated_by: str = "step_3_character_prompter"

class FFShotEntry(BaseModel):
    """First frame shot. Generated via Flux Klein 9B with char sheets as references.
    prompt_type 'extracted_frame' is reserved for Wave-2 continuation shots whose
    FF is the previous video's last frame (no generation needed).
    """
    prompt_type: str  # "flux_klein_t2i" or "extracted_frame"
    prompt: Optional[str] = None
    reference_images: list[str] = []  # char_sheet template refs in spatial-map order
    output_path: Optional[str] = None
    status: str = "pending"
    generated_by: str

class LFShotEntry(BaseModel):
    """Last frame shot. Generated via Flux Klein 9B with char sheets + FF as refs.
    reference_images order: char sheets first, then {{ff_shots.SHOT.output_path}}.
    The FF ref anchors structural / environmental continuity; char sheets anchor identity.
    """
    prompt_type: str = "flux_klein_t2i"
    prompt: Optional[str] = None
    reference_images: list[str] = []  # char_sheets first, then {{ff_shots.SHOT.output_path}}
    output_path: Optional[str] = None
    status: str = "pending"
    generated_by: str = "step_6_lf_prompter"

class CharacterSpatialEntry(BaseModel):
    """One character's placement within a shot. Listed per shot_id in
    `character_spatial_map`. Drives per-character-anchored FF/LF prompts so the
    Flux Klein 9B model can match each ref image to a specific on-screen figure
    (avoids identity swaps on multi-character shots)."""
    character_id: str
    reference_index: int
    screen_position: str
    visual_identifier: str
    action: str

class MotionPromptEntry(BaseModel):
    """LTX-2.3 FLF2V motion prompt. Generated by a 3-cycle reflexion loop
    (generator + critic with exit_loop tool)."""
    prompt: Optional[str] = None
    duration_seconds: int
    ff_image: Optional[str] = None  # {{ff_shots.SHOT.output_path}}
    lf_image: Optional[str] = None  # {{lf_shots.SHOT.output_path}}
    output_path: Optional[str] = None
    status: str = "pending"
    generated_by: str = "step_7_motion_prompter"

class LFDeltaPlanEntry(BaseModel):
    delta_type: str

class PromptsFile(BaseModel):
    meta: PromptsMeta
    character_sheets: dict[str, CharacterSheetEntry] = {}
    ff_shots: dict[str, FFShotEntry] = {}
    lf_shots: dict[str, LFShotEntry] = {}
    lf_delta_plan: dict[str, str] = {}
    character_spatial_map: dict[str, list[CharacterSpatialEntry]] = {}
    motion_prompts: dict[str, MotionPromptEntry] = {}
