#!/usr/bin/env python3
"""Export human-readable shared-asset manifests (CHARACTERS.md, LOCATIONS.md,
OBJECTS.md) into the shared assets dir.

Several authoring prompts tell agents to read ``assets/CHARACTERS.md`` for
existing character ids and wardrobe — this script makes that file real. Each
file is generated (do not hand-edit) from:

  * the ``## Characters`` / ``## Locations`` / ``## Objects`` sections of the
    current episode's ``developed_story.md``, annotated with
  * the shared ``asset_registry.json`` entries (asset file path + hosted URL).

  python3 scripts/export_assets_manifest.py --output-dir <run> [--assets-dir <dir>]

Called automatically at the end of ``build_images.py --assets-only``; runnable
standalone to (re)index existing assets.
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SKILL_ROOT))


def _extract_section(md: str, header: str) -> str:
    """Return the body of a '## <header>' section (up to the next '## ')."""
    lines = md.splitlines()
    out: list[str] = []
    in_sec = False
    for line in lines:
        if line.startswith(f"## {header}"):
            in_sec = True
            continue
        if in_sec and line.startswith("## "):
            break
        if in_sec:
            out.append(line)
    return "\n".join(out).strip()


def _load_registry(assets_dir: str) -> dict:
    path = os.path.join(assets_dir, "asset_registry.json")
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except (json.JSONDecodeError, OSError):
        return {}


def _registry_lines(entries: dict) -> list[str]:
    lines = []
    for asset_id in sorted(entries):
        e = entries[asset_id] or {}
        path = e.get("output_path") or "(not generated yet)"
        hosted = "uploaded" if e.get("fal_image_url") else "local-only"
        lines.append(f"- `{asset_id}` — {path} ({hosted})")
    return lines


def _registry_lines_v2(assets: dict, kind: str) -> list[str]:
    """Registry lines for the h3 schema: status, variant, lock_hash, path."""
    lines = []
    entries = [e for e in assets.values() if e.get("kind") == kind]
    for e in sorted(entries, key=lambda x: x.get("asset_id", "")):
        cur = e.get("current") or 0
        ver = next(
            (v for v in (e.get("versions") or []) if v.get("v") == cur),
            (e.get("versions") or [{}])[-1] if e.get("versions") else {},
        )
        path = ver.get("path") or e.get("output_path") or "(not generated yet)"
        lock = (e.get("lock_hash") or "unknown")[:16]
        lines.append(
            f"- `{e.get('entity_id')}` [{e.get('status', '?')}, "
            f"{e.get('variant', 'base')}] — {path} — lock {lock}…"
        )
    return lines


def _is_v2(registry: dict) -> bool:
    return isinstance(registry.get("assets"), dict)


def export_manifests(run_dir: str, assets_dir: str) -> list[str]:
    """Write CHARACTERS.md / LOCATIONS.md / OBJECTS.md into assets_dir."""
    story_path = os.path.join(run_dir, "developed_story.md")
    story_md = ""
    if os.path.isfile(story_path):
        with open(story_path, encoding="utf-8") as f:
            story_md = f.read()

    registry = _load_registry(assets_dir)
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    written: list[str] = []

    for section, section_name, filename, kind in (
        ("characters", "Characters", "CHARACTERS.md", "character_plate"),
        ("locations", "Locations", "LOCATIONS.md", "location_lock"),
        ("objects", "Objects", "OBJECTS.md", "prop"),
    ):
        body = _extract_section(story_md, section_name)
        if _is_v2(registry):
            reg_lines = _registry_lines_v2(registry["assets"], kind)
        else:
            reg_lines = _registry_lines(registry.get(section, {}))
        content = (
            f"# {section_name} — shared asset manifest\n\n"
            f"Generated by scripts/export_assets_manifest.py on {stamp} — "
            "do not edit by hand; update developed_story.md or the asset "
            "registry and re-export.\n\n"
        )
        if body:
            content += f"## From developed_story.md\n\n{body}\n\n"
        else:
            content += "## From developed_story.md\n\n_(no developed_story.md found in this run)_\n\n"
        content += "## Registry\n\n"
        content += "\n".join(reg_lines) if reg_lines else "_(empty)_"
        content += "\n"

        out = os.path.join(assets_dir, filename)
        with open(out, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(out)
    return written


def main() -> int:
    p = argparse.ArgumentParser(description="Export CHARACTERS/LOCATIONS/OBJECTS manifests")
    p.add_argument("--output-dir", required=True, help="run output dir (reads developed_story.md)")
    p.add_argument("--assets-dir", default=None,
                   help="shared assets dir (default: <output-dir>/../assets)")
    args = p.parse_args()

    run_dir = os.path.abspath(args.output_dir)
    assets_dir = args.assets_dir or os.path.join(os.path.dirname(run_dir), "assets")
    os.makedirs(assets_dir, exist_ok=True)

    written = export_manifests(run_dir, assets_dir)
    for w in written:
        print(f"wrote {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
